### ISSUE TITLE
when will you release your code ?

### ISSUE THREAD

**Issue by liuguoyou** [rvarun7777/FisheyeDistanceNet#1]

**Comment by hbaradius** [comment]
Indeed, I was also wondering if we can try out the code anytime soon? The github repository only contains svgs.
Thank you

**Comment by VitorGuizilini-TRI** [comment]
I am wondering the same, when will code be made available? Thank you!

**Comment by rvarun7777** [comment]
Sorry for the delayed response. We are waiting to release the WoodScape dataset first. Following its release, you can expect initial incremental versions of the code.

**Comment by chop0** [comment]
I was wondering if there was any update on this

**Comment by liuguoyou** [comment]
WoodScape Already released，will you release the code？

**Comment by rvarun7777** [comment]
It is released! Kindly check the official repo.

**Comment by HolmesShuan** [comment]
@rvarun7777 Hi, could you please release the code? It seems that the official repo only contains svgs.

**Comment by rvarun7777** [comment]
@HolmesShuan  
https://github.com/valeoai/WoodScape/tree/master/omnidet

**Comment by HU75** [comment]
@rvarun7777 Hi, thank you for your contribution to fisheye perception! I would like to ask if the soiling detection part is open source in omnidet?
